Scaffolding
KartoonYoko/gophkeeper pull request #1
Opened 2024-05-26 08:44 UTC by KartoonYoko

2024-06-17 09:06 UTC, tmvrus requested changes
```
go test ./... -cover
	github.com/KartoonYoko/gophkeeper/cmd/client		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/cmd/server		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/app/cliclient		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/app/server		coverage: 0.0% of statements
?   	github.com/KartoonYoko/gophkeeper/internal/storage/model/auth	[no test files]
?   	github.com/KartoonYoko/gophkeeper/internal/storage/model/filestore	[no test files]
?   	github.com/KartoonYoko/gophkeeper/internal/storage/model/store	[no test files]
	github.com/KartoonYoko/gophkeeper/internal/controller/cliclient		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/logger		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/storage/common		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/storage/clientstorage		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/proto		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/controller/grpcserver		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/storage/error/auth		coverage: 0.0% of statements
?   	github.com/KartoonYoko/gophkeeper/internal/usecase/model/auth	[no test files]
	github.com/KartoonYoko/gophkeeper/internal/storage/miniostorage		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/usecase/auth		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/storage/postgres		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/usecase/clientstore		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/usecase/clientauth		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/usecase/clientversion		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/usecase/common		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/usecase/common/cliclient		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/usecase/model/store		coverage: 0.0% of statements
	github.com/KartoonYoko/gophkeeper/internal/usecase/store		coverage: 0.0% of statements
ok  	github.com/KartoonYoko/gophkeeper/internal/common	0.714s	coverage: 33.8% of statements
```
<img width="726" alt="image" src="https://github.com/KartoonYoko/gophkeeper/assets/554425/1e69845c-3929-45cc-b97d-adf42c3dccc0">

2024-06-17 09:06 UTC, tmvrus commented on internal/common/doc.go
`common` не самое удачное название для пакета, потому что ничего не говорит о его содержимом, рекомендую выбирать "говорящие" имена для пакетов

2024-06-18 23:25 UTC, KartoonYoko commented on internal/common/doc.go
Теперь в директории common лежат общие пакеты. Такой подход будет лучше?

2024-06-18 23:46 UTC, KartoonYoko commented
В этом случае даёт покрытие 80%, но при "go test --cover ./..." только 60%. 
![grpcservercover](https://github.com/KartoonYoko/gophkeeper/assets/55305327/91853e58-8a41-444c-80c0-5900e766a7be)

2024-06-19 08:22 UTC, tmvrus commented on internal/common/doc.go
да, теперь понятно что за что отвечает

2024-06-19 10:39 UTC, tmvrus approved these changes
Поздравляю

2024-06-19 10:39 UTC, tmvrus commented on internal/controller/cliclient/dataCreateCmd.go
> +	}
эти строки по многу раз в проекте повторяются, разумно сделать их константами

2024-06-19 10:39 UTC, tmvrus commented on internal/controller/cliclient/dataGetCmd.go
> +			cmd.Printf("Description: %s\nNumber: %s\nCVV: %s\n", r.Description, r.Number, r.CVV)
такое удобно делать при помощи табличных методов
https://vk.com/wall-51126445_31872
читаемость существенно повышается

2024-06-19 10:39 UTC, tmvrus commented on internal/proto/store.proto
> +    DATA_TYPE_CREDENTIALS = 0;
обычно первым элементом делают что-то типа DATA_TYPE_INVALID = 0 что бы отличить zero-value который назначается автоматом, от валидных значений кототрые нужно передать явно

2024-06-19 10:39 UTC, tmvrus commented on internal/storage/clientstorage/migrations/20240608234926_init.sql
> +    data_type TEXT,
тут тоже можно было сделать enum, даже  sqlite  как-то умеет

2024-06-19 10:39 UTC, tmvrus commented on internal/storage/clientstorage/storage.go
> +func (s *Storage) SaveCredentials(ctx context.Context, at string, rt string, sk string, userID string) error {
когда одинаковые типы идут подряд
` at string, rt string, sk string, userID string`
можно экономить и писать вот так
` at, rt , sk, userID string`

2024-07-03 12:21 UTC, merged